"""adding a purchase option to products table

Revision ID: 12197eb22d42
Revises: b7c8f380746b
Create Date: 2025-01-12 16:42:22.399812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12197eb22d42'
down_revision = 'b7c8f380746b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('purchase_date')

    # ### end Alembic commands ###
