"""adding email confirmation to users

Revision ID: d76a3cdc0b9c
Revises: 5dbf7646296f
Create Date: 2025-01-10 18:45:14.865614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76a3cdc0b9c'
down_revision = '5dbf7646296f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed_on')
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('email_confirmation_sent_on')
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###
